import 'package:flutter/material.dart';
import 'package:news_application/model/news_model.dart';
import 'package:news_application/presentation/views/authentication/forgot_password.dart';
import 'package:news_application/presentation/views/authentication/login_method.dart';
import 'package:news_application/presentation/views/authentication/signin.dart';
import 'package:news_application/presentation/views/authentication/signin_signup.dart';
import 'package:news_application/presentation/views/authentication/signup.dart';
import 'package:news_application/presentation/views/main/categories/categories_page.dart';
import 'package:news_application/presentation/views/main/home/home_page.dart';
import 'package:news_application/presentation/views/main/main_page.dart';
import 'package:news_application/presentation/views/main/settings/settings_screen.dart';
import 'package:news_application/presentation/views/main/storage/my_own_news.dart';
import 'package:news_application/presentation/views/main/storage/recent_view.dart';
import 'package:news_application/presentation/views/main/storage/save_news.dart';
import 'package:news_application/presentation/views/main/setup/setup_screen.dart';
import 'package:news_application/presentation/views/start/onboard.dart';
import 'package:news_application/presentation/views/start/splash_screen.dart';

Widget get loginMethod => LoginMethod();
Widget get splash => SplashScreen();
Widget get onboard => Onboard();
Widget get loginSignUp => SigninSignup();
Widget get signIn => Signin();
Widget get signUp => Signup();
Widget get forgotPassword => ForgotPassword();
Widget get mainPage => MainPage();
Widget get homePage => HomePage();
Widget get categoriesPage => CategoriesPage();
Widget get profile => SettingsScreen();
Widget get recentView => RecentView();
Widget get saveNews => SaveNews();
Widget get setup => SetupScreen();
Widget get myNews => MyOwnNews();
Widget newsItem(NewsModel? news) => newsItem(news);